package SPEDJob.processors

import SPEDJob.core.processor.SPEDBaseProcessor
import SPEDJob.models.SPEDConfig

object SPEDE310Processor extends SPEDBaseProcessor {
  override def registro: String = "E310"

  val config: SPEDConfig = super.config(
    """
      SELECT
        s.ID_PAI,
        s.ID,
        s.LINHA,
        s.ID_BASE,
        s.REG,
        CAST(s.IND_MOV_FCP_DIFAL AS STRING) AS IND_MOV_FCP_DIFAL,
        CAST(s.VL_SLD_CRED_ANT_DIFAL AS DECIMAL(18, 2)) AS VL_SLD_CRED_ANT_DIFAL,
        CAST(s.VL_TOT_DEBITOS_DIFAL AS DECIMAL(18, 2)) AS VL_TOT_DEBITOS_DIFAL,
        CAST(s.VL_OUT_DEB_DIFAL AS DECIMAL(18, 2)) AS VL_OUT_DEB_DIFAL,
        CAST(s.VL_TOT_CREDITOS_DIFAL AS DECIMAL(18, 2)) AS VL_TOT_CREDITOS_DIFAL,
        CAST(s.VL_OUT_CRED_DIFAL AS DECIMAL(18, 2)) AS VL_OUT_CRED_DIFAL,
        CAST(s.VL_SLD_DEV_ANT_DIFAL AS DECIMAL(18, 2)) AS VL_SLD_DEV_ANT_DIFAL,
        CAST(s.VL_DEDUCOES_DIFAL AS DECIMAL(18, 2)) AS VL_DEDUCOES_DIFAL,
        CAST(s.VL_RECOL_DIFAL AS DECIMAL(18, 2)) AS VL_RECOL_DIFAL,
        CAST(s.VL_SLD_CRED_TRANSPORTAR_DIFAL AS DECIMAL(18, 2)) AS VL_SLD_CRED_TRANSPORTAR_DIFAL,
        CAST(s.DEB_ESP_DIFAL AS DECIMAL(18, 2)) AS DEB_ESP_DIFAL,
        CAST(s.VL_SLD_CRED_ANT_FCP AS DECIMAL(18, 2)) AS VL_SLD_CRED_ANT_FCP,
        CAST(s.VL_TOT_DEB_FCP AS DECIMAL(18, 2)) AS VL_TOT_DEB_FCP,
        CAST(s.VL_OUT_DEB_FCP AS DECIMAL(18, 2)) AS VL_OUT_DEB_FCP,
        CAST(s.VL_TOT_CRED_FCP AS DECIMAL(18, 2)) AS VL_TOT_CRED_FCP,
        CAST(s.VL_OUT_CRED_FCP AS DECIMAL(18, 2)) AS VL_OUT_CRED_FCP,
        CAST(s.VL_SLD_DEV_ANT_FCP AS DECIMAL(18, 2)) AS VL_SLD_DEV_ANT_FCP,
        CAST(s.VL_DEDUCOES_FCP AS DECIMAL(18, 2)) AS VL_DEDUCOES_FCP,
        CAST(s.VL_RECOL_FCP AS DECIMAL(18, 2)) AS VL_RECOL_FCP,
        CAST(s.VL_SLD_CRED_TRANSPORTAR_FCP AS DECIMAL(18, 2)) AS VL_SLD_CRED_TRANSPORTAR_FCP,
        CAST(s.DEB_ESP_FC AS DECIMAL(18, 2)) AS DEB_ESP_FC,
        c.ULTIMA_EFD,
        c.PERIODO_0000,
        c.CPF AS CPF_0000,
        c.CNPJ AS CNPJ_0000,
        c.IE AS IE_0000,
        c.PERIODO AS PERIODO_SPED_BASE
      FROM input_reg s
      INNER JOIN r0000 c ON s.id_base = c.id_base
    """
  )
}